---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-subscription
  namespace: acm-subscriptions
spec:
  type: GitHub
  pathname: https://github.com/maheshd2/ztp-ran-manifests
