apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ztpspoketwo-subscription
  namespace: ztpspoketwo-subscription
  labels:
    app: ztpspoketwo-subscription
  annotations:
    apps.open-cluster-management.io/git-path: manifests/sites/ztpspoketwo
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: ztpspoketwo-subscription/ztpspoketwo-subscription 
  placement:
    local: true
